#!/usr/bin/env bash
# One-shot interactive bootstrap for audiorec.
#
# Run this ONCE after cloning the repo on a fresh Pi OS:
#   sudo bash scripts/setup.sh
#
# It will:
#   1. run install.sh (apt deps, user, venv, systemd units)
#   2. auto-detect your USB mic
#   3. prompt for Wasabi creds, web password, hostname
#   4. write /etc/audiorec/config.toml
#   5. set the hostname (so http://<name>.local works)
#   6. start all three services
#   7. show you the URL to open on your phone

set -euo pipefail

if [[ $EUID -ne 0 ]]; then
    echo "Please run as root: sudo bash scripts/setup.sh" >&2
    exit 1
fi

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CONFIG_DIR="/etc/audiorec"
CONFIG_FILE="$CONFIG_DIR/config.toml"
INSTALL_DIR="/opt/audiorec"
SERVICE_USER="audiorec"

c_bold() { printf '\033[1m%s\033[0m\n' "$*"; }
c_info() { printf '\033[36m>>> %s\033[0m\n' "$*"; }
c_warn() { printf '\033[33m!!! %s\033[0m\n' "$*"; }
c_ok()   { printf '\033[32m[OK] %s\033[0m\n' "$*"; }

ask() {
    local prompt="$1" default="${2:-}" var
    if [[ -n "$default" ]]; then
        read -r -p "$prompt [$default]: " var
        echo "${var:-$default}"
    else
        read -r -p "$prompt: " var
        echo "$var"
    fi
}

ask_secret() {
    local prompt="$1" var
    read -r -s -p "$prompt: " var
    echo >&2
    printf '%s' "$var"
}

# --- 1. run installer -----------------------------------------------------
c_info "Step 1/6: installing apt packages, user, venv, systemd units"
bash "$REPO_DIR/scripts/install.sh"

# --- 2. detect USB mic ----------------------------------------------------
c_info "Step 2/6: detecting USB microphone"
if ! command -v arecord >/dev/null; then
    c_warn "arecord not found; install failed?"
    exit 1
fi

MIC_LIST="$(arecord -l 2>/dev/null || true)"
echo "$MIC_LIST"
echo

# Pick first card that looks like USB (skip bcm2835 builtins).
DETECTED_DEVICE=""
while IFS= read -r line; do
    if [[ "$line" =~ ^card\ ([0-9]+):\ ([^[:space:]]+).*device\ ([0-9]+): ]]; then
        card="${BASH_REMATCH[1]}"
        name="${BASH_REMATCH[2]}"
        dev="${BASH_REMATCH[3]}"
        if [[ ! "$name" =~ [Bb]cm ]]; then
            DETECTED_DEVICE="hw:${card},${dev}"
            break
        fi
    fi
done <<< "$MIC_LIST"

if [[ -z "$DETECTED_DEVICE" ]]; then
    c_warn "Could not auto-detect a USB mic. Plug it in and re-run, or enter manually."
    DETECTED_DEVICE="hw:1,0"
fi

AUDIO_DEVICE="$(ask "ALSA device for the USB mic" "$DETECTED_DEVICE")"

# --- 3. interactive config ------------------------------------------------
c_info "Step 3/6: configuring"

HOSTNAME_DEFAULT="audiorec"
NEW_HOSTNAME="$(ask "mDNS hostname (your phone will use http://<name>.local)" "$HOSTNAME_DEFAULT")"

echo
c_bold "Wasabi credentials"
echo "Create a bucket and access key at https://console.wasabisys.com if you haven't."
WASABI_ACCESS="$(ask "Wasabi access key")"
WASABI_SECRET="$(ask_secret "Wasabi secret key")"
WASABI_BUCKET="$(ask "Wasabi bucket name")"
WASABI_REGION="$(ask "Wasabi region" "us-east-1")"
WASABI_ENDPOINT_DEFAULT="https://s3.${WASABI_REGION}.wasabisys.com"
WASABI_ENDPOINT="$(ask "Wasabi endpoint URL" "$WASABI_ENDPOINT_DEFAULT")"
WASABI_PREFIX="$(ask "Key prefix (folder) inside the bucket" "recordings/")"

echo
c_bold "Web UI login"
WEB_USER="$(ask "Username" "admin")"
while true; do
    WEB_PW1="$(ask_secret "Password (min 6 chars)")"
    if [[ ${#WEB_PW1} -lt 6 ]]; then
        c_warn "Too short, try again."
        continue
    fi
    WEB_PW2="$(ask_secret "Confirm password")"
    if [[ "$WEB_PW1" != "$WEB_PW2" ]]; then
        c_warn "Passwords did not match, try again."
        continue
    fi
    break
done

c_info "Hashing password"
PW_HASH="$(printf '%s' "$WEB_PW1" | "$INSTALL_DIR/venv/bin/python" -c '
import bcrypt, sys
pw = sys.stdin.buffer.read()
print(bcrypt.hashpw(pw, bcrypt.gensalt()).decode())
')"

SESSION_SECRET="$(openssl rand -hex 32)"

# --- 4. write config ------------------------------------------------------
c_info "Step 4/6: writing $CONFIG_FILE"

# Back up any existing config just in case.
if [[ -f "$CONFIG_FILE" ]]; then
    cp -a "$CONFIG_FILE" "$CONFIG_FILE.bak.$(date +%s)"
fi

cat > "$CONFIG_FILE" <<EOF
# Generated by scripts/setup.sh on $(date -Iseconds)

[paths]
data_dir = "/var/lib/audiorec"
recordings_subdir = "recordings"

[audio]
device = "$AUDIO_DEVICE"
sample_rate = 16000
channels = 1
format = "S16_LE"

[gpio]
button_pin = 17
led_pin = 18
debounce_s = 0.05
long_press_s = 3.0

[upload]
poll_interval_s = 5
local_retention_days = 7
opus_bitrate = "24k"
multipart_part_size_mb = 5
max_retries = 10

[wasabi]
access_key = "$WASABI_ACCESS"
secret_key = "$WASABI_SECRET"
endpoint_url = "$WASABI_ENDPOINT"
region = "$WASABI_REGION"
bucket = "$WASABI_BUCKET"
key_prefix = "$WASABI_PREFIX"

[web]
host = "0.0.0.0"
port = 80
username = "$WEB_USER"
password_hash = "$PW_HASH"
session_secret = "$SESSION_SECRET"
session_lifetime_s = 2592000
hostname = "$NEW_HOSTNAME.local"
EOF

chown root:"$SERVICE_USER" "$CONFIG_FILE"
chmod 0640 "$CONFIG_FILE"
c_ok "wrote $CONFIG_FILE"

# --- 5. hostname ----------------------------------------------------------
c_info "Step 5/6: setting system hostname to '$NEW_HOSTNAME'"
CURRENT_HOSTNAME="$(hostname)"
if [[ "$CURRENT_HOSTNAME" != "$NEW_HOSTNAME" ]]; then
    hostnamectl set-hostname "$NEW_HOSTNAME"
    # Also update /etc/hosts so `sudo` stays quick.
    if grep -q "127.0.1.1" /etc/hosts; then
        sed -i "s/^127.0.1.1.*/127.0.1.1\t$NEW_HOSTNAME/" /etc/hosts
    else
        echo -e "127.0.1.1\t$NEW_HOSTNAME" >> /etc/hosts
    fi
    systemctl restart avahi-daemon || true
fi

# --- 6. start services ----------------------------------------------------
c_info "Step 6/6: starting services"
systemctl daemon-reload
systemctl restart audiorec-recorder audiorec-uploader audiorec-webapp

sleep 2
for svc in audiorec-recorder audiorec-uploader audiorec-webapp; do
    if systemctl is-active --quiet "$svc"; then
        c_ok "$svc is running"
    else
        c_warn "$svc failed to start - check 'journalctl -u $svc -n 30'"
    fi
done

IP="$(hostname -I | awk '{print $1}')"
echo
c_bold "=========================================================="
c_bold "  Done! Open on your phone (same WiFi):"
echo   "    http://$NEW_HOSTNAME.local"
echo   "    http://$IP              (fallback if .local doesn't resolve)"
echo
echo   "  Press your button (GPIO17 to GND) to start/stop recording."
echo   "  Tail the recorder: journalctl -fu audiorec-recorder"
c_bold "=========================================================="
